In [1]:
import numpy as np
import pandas as pd
import os
import warnings
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
path='C:\\Users\\User\\Documents\\Zomato Restaurant Project\\dataset'
dataset=pd.read_csv(os.path.join(path,'zomato.csv'),encoding='latin-1')

In [27]:
dataset.shape

(9551, 21)

In [28]:
dataset.head(2)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591

In [31]:
cuisine=(dataset.assign(Cuisines_new=dataset['Cuisines'].str.split(',')).explode('Cuisines_new'))

In [33]:
cuisine.shape

(19719, 22)

In [35]:
cuisine.dropna(inplace=True)

In [36]:
cuisine.shape

(19710, 22)

In [37]:
cuisine['Rating color'].value_counts()

Rating color
Orange        7589
Yellow        4926
White         3443
Green         2646
Dark Green     678
Red            428
Name: count, dtype: int64

In [5]:
dataset.to_excel("dataset.xlsx")

<h1> Cases:</h1>
<ol>
    <li>show top 10 similar restaurants to the one user selected based on cuisines filter by city.
    <li>conditions:locality is given by user,top 10 similar restaurants in locality by cuisines.
    <li>conditions: minimum rating given
        <ul>
            <li>price range is not given-->sort them from primium to cheap</li>
            <li>price range is given-->filter by price range and then sort them in desc</li>
        </ul></li>
    <li>conditions: when ratings,price range,table booking,online delivery -->re rank them based on condition</li>
</ol>

In [46]:
def preprocess(path,code_path):
    df=pd.read_csv(path,encoding='latin-1')
    country_df=pd.read_excel(code_path)
    merge_df=df.merge(country_df,on='Country Code',how='left')
    merge_df.drop(columns=['Country Code','Is delivering now','Switch to order menu','Rating color','Locality Verbose','Currency'],inplace=True)
    merge_df.dropna(axis=0,inplace=True)
    merge_df.drop_duplicates(inplace=True)
    merge_df=merge_df.loc[merge_df['Country']=='India']
    merge_df.to_csv("final_dataset.csv")

In [110]:
class Recommendation_System():
    def __init__(self):
        self.sim_matrix=None
        self.dataset=None
        self.tfidf_matrix=None
        self.index=None
        
    def load_data(self,file_path):
        dataset_path=file_path
        df=pd.read_csv(dataset_path,encoding='latin-1')
        df['Cuisines']=df['Cuisines'].str.split(',').apply(lambda x: [val.strip().replace(" ","_") for val in x])
        df['Cuisines_processed']=df['Cuisines'].apply(lambda x: " ".join(x))
        
        df['Combined_col']=(
            df['Restaurant Name'].str.lower()+" "+
            df['City'].str.lower()+" "+
            df['Locality'].str.lower()+" "+
            df['Cuisines_processed'].str.lower()
        )
        if "Unnamed: 0" in df.columns:
            df.drop(columns=['Unnamed: 0'],inplace=True)
        self.dataset=df
        print(f'Successfully loaded and process the dataset {self.dataset.shape}')
        return self.dataset.head()

    def model_develop(self):
        if self.dataset is None:
            raise ValueError("Load the data first using the load_data().")
        df=self.dataset
        tfidf=TfidfVectorizer(
            max_features=5000,
            ngram_range=(1,2),
            lowercase=True,
            stop_words='english'
        )
        vectors=tfidf.fit_transform(df['Combined_col'])
        similarity_matrix=cosine_similarity(vectors,vectors)
        
        restaurant_idx=dict(zip(df['Restaurant ID'],df.index))
        self.sim_matrix=similarity_matrix
        self.index=restaurant_idx
        self.tfidf_matrix=vectors
        print(f"model successfully build, {similarity_matrix.shape}")

    def name_to_id(self,Restaurant_name,city_hint=False):
        match=self.dataset[self.dataset['Restaurant Name'].str.lower()==Restaurant_name.lower()]
        if match.empty:
            return None
        if len(match)==1:
            return match.iloc[0]['Restaurant ID']
        if city_hint:
            match=match[match['City'].str.lower().str.contains(city_hint.lower())]
            if len(match)==1:
                return match.iloc[0]['Restaurant ID']
            if len(match)==0:
                return None
        match=match.sort_values(by=['Aggregate rating','Votes'],ascending=[False,False])
        print(f"Multiple branches exists for restaurant {Restaurant_name}. Selected the highest rated one.")
        self.print_restaurant_branch(match.head(5))
        return match.iloc[0]['Restaurant ID']
            
        
    def print_restaurant_branch(self,restaurant_branch):
        columns=['Restaurant Name','Cuisines_processed','Locality','City','Has Table booking','Has Online delivery','Average Cost for two','Aggregate rating']
        print(f'Printing the top 5 Branches for the restaurant {restaurant_branch.iloc[0]['Restaurant Name']}')
        print(restaurant_branch[columns].to_string(index=False))
        print("=="*100)

    def get_recommendation(self,name,n,city):
        result=self.name_to_id(name,city)
        if result is None:
            return f"Restaurant{name} not available."
        
        rest_idx=self.index[result]
        score=list(enumerate(self.sim_matrix[rest_idx]))
        sort_score=sorted(score,key=lambda x:x[1],reverse=True)
        
        top_n=sort_score[1:n+1]
        top_index=[i[0] for i in top_n]
        
        recommend=self.dataset.iloc[top_index].copy()
        recommend['similarity_score']=[i[1] for i in top_n]
        return recommend[['Restaurant Name', 'City', 'Locality', 'Cuisines_processed', 
                          'Aggregate rating', 'Votes', 'similarity_score']]
    
    def recommendation_by_cuisines(
        self,
        preferred_cuisines,
        n_recommendations,
        min_rating=None,
        city=None,
        preferred_restaurant=None
    ):
        user_cuisines=[cuisine.strip().replace(' ','_').lower() for cuisine in preferred_cuisines]
        def Has_preferred_cuisine(row):
            if pd.isna(row['Cuisines_processed']):
                print('Cuisines is not available.')
                return False
            restaurant_cuisine=[c.lower().strip() for c in row['Cuisines_processed'].split(' ')]
            return any(p in restaurant_cuisine for p in user_cuisines)
        filtered_data=self.dataset[self.dataset.apply(Has_preferred_cuisine,axis=1)].copy()
        if city:
            filtered_data=filtered_data[filtered_data["City"].str.lower().str.strip().str.contains(city.lower())]
        if min_rating is not None:
            filtered_data=filtered_data[filtered_data['Aggregate rating']>=min_rating]

        if filtered_data.shape[0]==0:
            print('No Restaurants are available')
            return pd.DataFrame()
        
        if preferred_restaurant:
            ref_name=preferred_restaurant.lower()
            if ref_name not in self.dataset['Restaurant Name'].str.lower().tolist():
                print('Restaurant Not Available.')
                return pd.DataFrame()
            else:
                rest_id=self.name_to_id(ref_name,city)
                if not rest_id:
                    print(f"No Restaurant with name {preferred_restaurant} available.")
                idx=self.index[rest_id]
                sim_score=self.sim_matrix[idx]
                filter_indice=filtered_data.index
                filtered_sim_score=sim_score[filter_indice]
                sorted_idx = np.argsort(filtered_sim_score)[::-1]
                top_indices = filter_indice[sorted_idx][:n_recommendations]
                
                result = self.dataset.loc[top_indices].copy()
                result['similarity_score'] = filtered_sim_score[sorted_idx][:n_recommendations]
        else:
            result=filtered_data.sort_values(by=['Votes','Aggregate rating'],ascending=[False,False])[:n_recommendations]
        columns=['Restaurant Name', 'City', 'Cuisines', 'Aggregate rating', 'Votes', 'Price range']
        if 'similarity_score' in result.columns:
            columns.append('similarity_score')
        return result[columns].reset_index(drop=True)

In [111]:
path='C:\\Users\\User\\Documents\\Zomato Restaurant Project'
# preprocess(os.path.join(path,'zomato.csv'),os.path.join(path,'Country-Code.xlsx'))

In [113]:
rs = Recommendation_System()
rs.load_data(os.path.join(path,'final_dataset.csv'))
# rs.model_develop()

# # # Simple similarity
# # print(rs.get_recommendation("Domino's Pizza", n=6, city="New Delhi"))

# # # Cuisine filtered
# recs = rs.recommendation_by_cuisines(
#     preferred_cuisines=["South Indian", "Kerala"],
#     n_recommendations=5,
#     min_rating=4.0,
#     city="Delhi",
#     preferred_restaurant="Saravana Bhavan"
# )
# print(recs)

Successfully loaded and process the dataset (8652, 18)

,Restaurant ID,Restaurant Name,City,Address,Locality,Longitude,Latitude,Cuisines,Average Cost for two,Has Table booking,Has Online delivery,Price range,Aggregate rating,Rating text,Votes,Country,Cuisines_processed,Combined_col
0,3400025,Jahanpanah,Agra,"E 23, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,78.011544,27.161661,"[North_Indian, Mughlai]",850,No,No,3,3.9,Good,140,India,North_Indian Mughlai,jahanpanah agra agra cantt north_indian mughlai
1,3400341,Rangrezz Restaurant,Agra,"E-20, Shopping Arcade, Sadar Bazaar, Agra Cant...",Agra Cantt,0.000000,0.000000,"[North_Indian, Mughlai]",700,No,No,2,3.5,Good,71,India,North_Indian Mughlai,rangrezz restaurant agra agra cantt north_indi...
2,3400005,Time2Eat - Mama Chicken,Agra,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra Cantt,78.011608,27.160832,[North_Indian],500,No,No,2,3.6,Good,94,India,North_Indian,time2eat - mama chicken agra agra cantt north_...
3,3400021,Chokho Jeeman Marwari Jain Bhojanalya,Agra,"1/48, Delhi Gate, Station Road, Raja Mandi, Ci...",Civil Lines,77.998092,27.195928,[Rajasthani],400,No,No,2,4.0,Very Good,87,India,Rajasthani,chokho jeeman marwari jain bhojanalya agra civ...
4,3400017,Pinch Of Spice,Agra,"23/453, Opposite Sanjay Cinema, Wazipura Road,...",Civil Lines,78.007553,27.201725,"[North_Indian, Chinese, Mughlai]",1000,No,No,3,4.2,Very Good,177,India,North_Indian Chinese Mughlai,pinch of spice agra civil lines north_indian c...